<?php
namespace User\Model;

use Common\Map\IsSure;
use User\Bean\ShippingAddressBean;

class ShippingAddressModel extends AbstractModel{

    /**
     * @return ShippingAddressBean
     */
    protected function getBean()
    {
        return parent::getBean(); // TODO: Change the autogenerated stub
    }

    /**
     * @param \library\Mysql $model
     * @return \library\Mysql
     */
    private function bindWhere($model)
    {
        $bean = $this->getBean();
        $bean->getId()              && $model->in('id', $bean->getId());
        $bean->getUid()             && $model->equalTo('uid',$bean->getUid());
        $bean->getIsDefault()       && $model->equalTo('is_default',$bean->getIsDefault());
        $bean->getContactUser()     && $model->like('contact_user',"%".$bean->getContactUser()."%");
        $bean->getContactMobile()   && $model->like('contact_mobile',"%".$bean->getContactMobile()."%");
        $bean->getRegion()          && $model->like('region',"%".$bean->getRegion()."%");
        $bean->getAddress()         && $model->like('address',"%".$bean->getAddress()."%");
        $bean->getTag()             && $model->like('tag',"%".$bean->getTag()."%");
        return $model;
    }

    /**
     * 获取列表
     * @return array
     */
    public function getList(){
        $bean = $this->getBean();
        $model = $this->db()->table('user_shipping_address');
        $model = $this->bindWhere($model);
        $model->limit($bean->getLimit());
        if($bean->getPage()){
            $result = $model->page($bean->getPageCurrent(),$bean->getPagePer());
        }else{
            $result = $model->multi();
        }
        return $this->success($result);
    }

    /**
     * 根据ID获取信息
     * @return array
     */
    public function getInfo(){
        $model = $this->db()->table('user_shipping_address');
        $model = $this->bindWhere($model);
        $result = $model->one();
        return $this->success($result ? $result : array());
    }

    /**
     * 新增
     * @return array
     */
    public function add() {
        $bean = $this->getBean();
        if(!$bean->getUid())            return $this->error('参数错误');
        if(!$bean->getRegion())         return $this->error('请选择地区');
        if(!$bean->getAddress())        return $this->error('请填写详细地址');
        if(!$bean->getContactUser())    return $this->error('请填写联系人');
        if(!$bean->getContactMobile())  return $this->error('请填写联系人手机');

        $one = $this->db()->table('user_shipping_address')->field('id')->equalTo('uid',$bean->getUid())->one();
        if(empty($one['id'])){
            $isDefault = IsSure::yes;
        }else{
            $isDefault = $bean->getIsDefault() ? $bean->getIsDefault() : IsSure::no;
        }
        $this->db()->beginTrans();
        try{

            //if this set yes then others set no
            if($isDefault == IsSure::yes){
                $this->db()->table('user_shipping_address')->equalTo('uid',$bean->getUid())->update(array('is_default'=>IsSure::no));
            }

            $data = array();
            $data['uid'] = $bean->getUid();
            $data['region'] = $bean->getRegion();
            $data['address'] = $bean->getAddress();
            $data['contact_user'] = $bean->getContactUser();
            $data['contact_mobile'] = $bean->getContactMobile();
            $data['is_default'] = $isDefault;
            $bean->getTag() && $data['tag'] = $bean->getTag();
            if(!$this->db()->table('user_shipping_address')->insert($data)){
                throw new \Exception($this->db()->getError());
            }
            $id = $this->db()->lastInsertId();
        }catch (\Exception $e){
            $this->db()->rollBackTrans();
            return $this->error($e->getMessage());
        }
        $this->db()->commitTrans();
        return $this->success($id);
    }

    /**
     * 编辑
     * @return array
     */
    public function edit(){
        $bean = $this->getBean();
        if(!$bean->getId()) return $this->error('参数错误');
        $one = $this->db()->table('user_shipping_address')->field('id,uid')->equalTo('id',$bean->getId())->one();
        if($bean->getAuthUid()!=$one['uid']){
            return $this->error('权限错误');
        }
        try{
            $data = array();
            $bean->getRegion()          && $data['region'] = $bean->getRegion();
            $bean->getAddress()         && $data['address'] = $bean->getAddress();
            $bean->getContactUser()     && $data['contact_user'] = $bean->getContactUser();
            $bean->getContactMobile()   && $data['contact_mobile'] = $bean->getContactMobile();
            $bean->getTag()             && $data['tag'] = $bean->getTag();
            $this->db()->table('user_shipping_address')->equalTo('id',$bean->getId())->update($data);
        }catch (\Exception $e){
            return $this->error($e->getMessage());
        }
        return $this->success();
    }


    /**
     * 删除
     * @return array
     */
    public function del(){
        $bean = $this->getBean();
        if(!$bean->getId()) return $this->error('参数丢失');
        $one = $this->db()->table('user_shipping_address')->equalTo('id',$bean->getId())->field('id,uid')->one();
        if($bean->getAuthUid()!=$one['uid']){
            return $this->error('权限错误');
        }
        try{
            $this->db()->table('user_shipping_address')->in('id',$bean->getId())->delete();
        }catch (\Exception $e){
            return $this->error($e->getMessage());
        }
        return $this->success();
    }

    /**
     * @return array
     */
    public function setIsDefault(){
        $bean = $this->getBean();
        if(!$bean->getId()) return $this->error('参数丢失');
        $one = $this->db()->table('user_shipping_address')->equalTo('id',$bean->getId())->field('id,uid')->one();
        if($bean->getAuthUid()!=$one['uid']){
            return $this->error('权限错误');
        }
        $this->db()->beginTrans();
        try{
            //all set no
            $this->db()->table('user_shipping_address')->equalTo('uid',$one['uid'])->update(array('is_default'=>IsSure::no));
            $this->db()->table('user_shipping_address')->equalTo('id',$bean->getId())->update(array('is_default'=>IsSure::yes));
        }catch (\Exception $e){
            $this->db()->rollBackTrans();
            return $this->error($e->getMessage());
        }
        $this->db()->commitTrans();
        return $this->success();
    }

}