<?php
/**
 * @date: 2018/09/19
 */

namespace Data\Model;


class QQGroupModel extends AbstractModel
{

    /**
     * @return \Data\Bean\BookingBean
     */
    protected function getBean()
    {
        return parent::getBean(); // TODO: Change the autogenerated stub
    }

    /**
     * @param \library\Mysql $model
     * @return \library\Mysql
     */
    private function bindWhere($model)
    {
        $bean = $this->getBean();
        $bean->getId() && $model->in('id', $bean->getId());
        $bean->getName() && $model->like('name', "%" . $bean->getName() . "%");
        $bean->getNumber() && $model->like('number', "%" . $bean->getNumber() . "%");
        $bean->getBuildYear() && $model->like('build_year', "%" . $bean->getBuildYear() . "%");
        $bean->getDescription() && $model->like('description', "%" . $bean->getDescription() . "%");
        return $model;
    }

    /**
     * 获取列表
     * @return array
     */
    public function getList()
    {
        $bean = $this->getBean();
        $model = $this->db()->table('data_qq_group');
        $model = $this->bindWhere($model);
        ($bean->getOrderBy()) && $model->orderByStr($bean->getOrderBy());
        $model->orderBy('ordering', 'desc');
        if ($bean->getPage()) {
            $result = $model->page($bean->getPageCurrent(), $bean->getPagePer());
        } else {
            $result = $model->multi();
        }
        return $this->success($result);
    }

    /**
     * @return mixed
     */
    public function getInfo()
    {
        $model = $this->db()->table('data_qq_group');
        $model = $this->bindWhere($model);
        $result = $model->one();
        return $this->success($result);
    }

    /**
     * @return array
     */
    public function add()
    {
        $bean = $this->getBean();
        if (!$bean->getName()) return $this->error('请填写群名');
        if (!$bean->getNumber()) return $this->error('请当前群号');

        $data = array();
        $data['name'] = $bean->getName();
        $data['number'] = $bean->getNumber();
        ($bean->getBuildYear()) && $data['build_year'] = $bean->getBuildYear();
        ($bean->getDescription()) && $data['description'] = $bean->getDescription();
        ($bean->getPic()) && $data['pic'] = $bean->getPic();
        ($bean->getLink()) && $data['link'] = $bean->getLink();
        ($bean->getQty()) && $data['qty'] = $bean->getQty();
        try {
            if (!$this->db()->table('data_qq_group')->insert($data)) {
                throw new \Exception($this->db()->getError());
            }
            $id = $this->db()->lastInsertId();
        } catch (\Exception $e) {
            return $this->error($e->getMessage());
        }
        return $this->success($id);
    }

    /**
     * @return array
     */
    public function edit()
    {
        $bean = $this->getBean();
        if (!$bean->getId()) return $this->error('参数错误');

        $data = array();
        ($bean->getName()) && $data['name'] = $bean->getName();
        ($bean->getNumber()) && $data['number'] = $bean->getNumber();
        ($bean->getBuildYear()) && $data['build_year'] = $bean->getBuildYear();
        ($bean->getDescription()) && $data['description'] = $bean->getDescription();
        ($bean->getPic()) && $data['pic'] = $bean->getPic();
        ($bean->getLink()) && $data['link'] = $bean->getLink();
        ($bean->getQty()) && $data['qty'] = $bean->getQty();
        if ($data) {
            try {
                $this->db()->table('data_qq_group')->where(array('id' => $bean->getId()))->update($data);
            } catch (\Exception $e) {
                return $this->error($e->getMessage());
            }
        }
        return $this->success();
    }

    /**
     * @return array
     */
    public function del()
    {
        $bean = $this->getBean();
        if (!$bean->getId()) return $this->error('参数错误');
        try {
            $this->db()->table('data_qq_group')->where(array('id' => $bean->getId()))->delete();
        } catch (\Exception $e) {
            return $this->error($e->getMessage());
        }
        return $this->success();
    }

}