<?php

namespace Goods\Model;
/**
 * @date: 2018/09/29
 */
class GoodsAttrValueModel extends AbstractModel
{

    /**
     * @return \Goods\Bean\GoodsAttrValueBean
     */
    protected function getBean()
    {
        return parent::getBean(); // TODO: Change the autogenerated stub
    }

    /**
     * @param \library\Pgsql $model
     * @return \library\Pgsql
     */
    private function bindWhere($model)
    {
        $bean = $this->getBean();
        ($bean->getId()) && $model->in('id', $bean->getId());
        ($bean->getClassId()) && $model->in('class_id', $bean->getClassId());
        ($bean->getName()) && $model->like('name', "%" . $bean->getName() . "%");
        return $model;
    }

    /**
     * 获取
     * @return array
     */
    public function getList()
    {
        $bean = $this->getBean();
        $model = $this->db()->table('goods_attr_value');
        $model = $this->bindWhere($model);
        $model->orderBy('name', 'asc');
        if ($bean->getPagePer()) {
            $result = $model->page($bean->getPageCurrent(), $bean->getPagePer());
        } else {
            $result = $model->multi();
        }
        return $this->success($result);
    }

    /**
     * 取一条
     * @return array
     */
    public function getInfo()
    {
        $model = $this->db()->table('goods_attr_value');
        $model = $this->bindWhere($model);
        $result = $model->one();
        return $this->success($result);
    }

    /**
     * @return array
     */
    public function add()
    {
        $bean = $this->getBean();
        if (!$bean->getClassId()) return $this->error('缺少值');
        if (!$bean->getName()) return $this->error('缺少值');
        $data = array();
        $data['class_id'] = $bean->getClassId();
        $data['name'] = $bean->getName();
        $bean->getPic() && $data['pic'] = $bean->getPic();
        try {
            if (!$this->db()->table('goods_attr_value')->insert($data)) {
                throw new \Exception($this->db()->getError());
            }
            $id = $this->db()->lastInsertId();
        } catch (\Exception $e) {
            return $this->error($this->db()->getError());
        }
        return $this->success($id);
    }

    /**
     * @return array
     */
    public function edit()
    {
        $bean = $this->getBean();
        if (!$bean->getId()) return $this->error('参数错误');
        $data = array();
        $bean->getName() && $data['name'] = $bean->getName();
        $bean->getPic() && $data['pic'] = $bean->getPic();
        if ($data) {
            try {
                $this->db()->table('goods_attr_value')->equalTo('id', $bean->getId())->update($data);
            } catch (\Exception $e) {
                return $this->error($this->db()->getError());
            }
        }
        return $this->success();
    }

    public function del(){
        $bean = $this->getBean();
        if (!$bean->getId()) return $this->error('参数错误');
        try {
            $this->db()->table('goods_attr_value')->equalTo('id', $bean->getId())->delete();
        } catch (\Exception $e) {
            return $this->error($this->db()->getError());
        }
        return $this->success();
    }

}