<?php

namespace Goods\Model;

/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2015/9/17
 * Time: 10:56
 */
class GoodsCollectionModel extends AbstractModel
{

    const GoodsField = 'uid,name,pic,price_sell';

    /**
     * @return \Goods\Bean\GoodsCollectionBean
     */
    protected function getBean()
    {
        return parent::getBean(); // TODO: Change the autogenerated stub
    }

    private function getViewModel()
    {
        $table = $this->db()->table('goods_collection')
            ->join('goods_collection', 'goods', array('goods_id' => 'id'), 'left')
            ->field('*', 'goods_collection')
            ->field(self::GoodsField, 'goods');
        return $table;
    }

    /**
     * @param \library\Pgsql $model
     * @return \library\Pgsql
     */
    private function bindWhere($model)
    {
        $bean = $this->getBean();
        $model->whereTable('goods_collection');
        $bean->getId() && $model->equalTo('id', $bean->getId());
        $bean->getUid() && $model->equalTo('uid', $bean->getUid());
        $bean->getGoodsId() && $model->equalTo('goods_id', $bean->getGoodsId());
        $bean->getCreateTime() && $model->between('create_time', $bean->getCreateTime());
        $model->whereTable('goods');
        $bean->getName() && $model->like('name', '%' . $bean->getName() . '%');
        $model->whereTable(null);
        return $model;
    }

    /**
     * 获取
     * @return array
     */
    public function getList()
    {
        $bean = $this->getBean();
        $model = $this->getViewModel();
        $model = $this->bindWhere($model);
        if ($bean->getOrderBy()) {
            $model->orderByStr($bean->getOrderBy());
        } else {
            $model->orderBy('create_time', 'desc');
        }
        if ($bean->getPage()) {
            $result = $this->getViewModel()->page($bean->getPageCurrent(), $bean->getPagePer());
        } else {
            $result = $this->getViewModel()->multi();
        }
        return $this->success($result);
    }

    /**
     * 创建收藏
     * @return array
     */
    public function add()
    {
        $bean = $this->getBean();
        if (!$bean->getUid()) return $this->error('非法用户');
        if (!$bean->getGoodsId()) return $this->error('非法商品');
        $one = $this->db()->table('goods_collection')->field('id')->where(array('uid' => $bean->getUid(), 'goods_id' => $bean->getGoodsId()))->one();
        if ($one['id']) {
            return $this->error('已经收藏过了');
        }
        $data = array();
        $data['create_time'] = $this->db()->now();
        $data['uid'] = $bean->getUid();
        $data['goods_id'] = $bean->getGoodsId();
        try {
            if (!$id = $this->db()->table('goods_collection')->insert($data)) {
                throw new \Exception($this->db()->getError());
            }
        } catch (\Exception $e) {
            return $this->error($e->getMessage());
        }
        return $this->success($id);
    }

    /**
     * 根据ID删除收藏
     * @return array
     */
    public function del()
    {
        $bean = $this->getBean();
        try {
            if ($bean->getId()) {
                $this->db()->table('goods_collection')->where(array('id' => $bean->getId()))->delete();
            } elseif ($bean->getUid() && $bean->getGoodsId()) {
                $this->db()->table('goods_collection')->where(array('uid' => $bean->getUid(), 'goods_id' => $bean->getGoodsId()))->delete();
            }
        } catch (\Exception $e) {
            return $this->error($e->getMessage());
        }
        return $this->success();
    }

}