<?php

namespace Order\Model;

use Order\Bean\LogBean;

class LogModel extends AbstractModel
{

    /**
     * @return LogBean
     */
    protected function getBean()
    {
        return parent::getBean(); // TODO: Change the autogenerated stub
    }

    /**
     * @param \library\Pgsql $model
     * @return \library\Pgsql
     */
    private function bindWhere($model)
    {
        $bean = $this->getBean();
        $bean->getOrderId() && $model->in('order_id', $bean->getOrderId());
        $bean->getOperatorUid() && $model->in('operator_uid', $bean->getOperatorUid());
        return $model;
    }

    private function record($operator, $order_id, $operator_uid, $data)
    {
        if (!$order_id) return $this->false('参数错误：id');
        if (!$operator) return $this->false('参数错误：operator');
        $data['log_time'] = $this->getNowDateTime();
        $data['order_id'] = $order_id;
        $data['operator'] = $operator;
        ($operator_uid) && $data['operator_uid'] = $operator_uid;
        ($data) && $data['data'] = json_encode($data);
        try {
            if (!$this->db()->table('order_log')->insert($data)) {
                throw new \Exception($this->db()->getError());
            }
        } catch (\Exception $e) {
            return $this->false($e->getMessage());
        }
        return $this->true();
    }

    public function recordCreate__($order_id, $operator_uid, $data)
    {
        return $this->record('创建订单', $order_id, $operator_uid, $data);
    }

    public function recordCancel__($order_id, $operator_uid, $data)
    {
        return $this->record('取消订单', $order_id, $operator_uid, $data);
    }

    public function recordAutoCancel__($order_id, $operator_uid, $data)
    {
        return $this->record('系统自动取消订单', $order_id, $operator_uid, $data);
    }

    public function recordAutoCancelSeller__($order_id, $operator_uid, $data)
    {
        return $this->record('卖家不发货，系统自动取消订单', $order_id, $operator_uid, $data);
    }

    public function recordPay__($order_id, $operator_uid, $data)
    {
        return $this->record('支付订单', $order_id, $operator_uid, $data);
    }

    public function recordSend__($order_id, $operator_uid, $data)
    {
        return $this->record('订单发货', $order_id, $operator_uid, $data);
    }

    public function recordReceived__($order_id, $operator_uid, $data)
    {
        return $this->record('订单收货', $order_id, $operator_uid, $data);
    }

    public function recordReceivedAuto__($order_id, $operator_uid, $data)
    {
        return $this->record('订单自动收货', $order_id, $operator_uid, $data);
    }

    public function recordEvaluation__($order_id, $operator_uid, $data)
    {
        return $this->record('评价订单', $order_id, $operator_uid, $data);
    }

    public function recordEvaluationAuto__($order_id, $operator_uid, $data)
    {
        return $this->record('订单自动评价', $order_id, $operator_uid, $data);
    }

    public function recordApplyRefund__($order_id, $operator_uid, $data)
    {
        return $this->record('申请退款', $order_id, $operator_uid, $data);
    }

    public function recordSureRefund__($order_id, $operator_uid, $data)
    {
        return $this->record('确认已退款', $order_id, $operator_uid, $data);
    }

    /**
     * 获取列表
     * @return array
     */
    public function getList()
    {
        $bean = $this->getBean();
        $model = $this->db()->table('order_log');
        $model = $this->bindWhere($model);
        $model->orderBy('log_time', 'desc');
        if ($bean->getPage()) {
            $result = $model->page($bean->getPageCurrent(), $bean->getPagePer());
        } else {
            $result = $model->multi();
        }
        return $this->success($result);
    }

}
