<?php

namespace Order\Model;

use Order\Bean\OrderItemsBean;

class OrderItemsModel extends AbstractModel
{

    /**
     * @return OrderItemsBean
     */
    protected function getBean()
    {
        return parent::getBean(); // TODO: Change the autogenerated stub
    }

    /**
     * @param \library\Pgsql $model
     * @return \library\Pgsql
     */
    private function bindWhere($model)
    {
        $bean = $this->getBean();
        $bean->getId() && $model->in('id', $bean->getId());
        return $model;
    }

    /**
     * @return array
     */
    public function getInfo()
    {
        $model = $this->db()->table('order_items');
        $result = $this->bindWhere($model)->one();
        return $this->success($this->factoryData($result, function ($tempData) {
            foreach ($tempData as $k => $v) {
                $v['item_data'] && $tempData[$k]['item_data'] = json_decode($v['item_data'], true);
            }
        }));
    }

}
